-- Test Data Schema — Sensor-only telemetry for inference testing
-- Mirrors telemetry.* tables but WITHOUT health indicator columns.
-- Populated by SENSOR_ONLY output mode simulations.

CREATE TABLE IF NOT EXISTS test_data.gas_turbine_telemetry (
    telemetry_id BIGSERIAL PRIMARY KEY,
    turbine_id INT NOT NULL REFERENCES master_data.gas_turbines(turbine_id) ON DELETE CASCADE,
    sample_time TIMESTAMP NOT NULL,
    operating_hours FLOAT,
    speed_rpm FLOAT,
    speed_target_rpm FLOAT,
    egt_celsius FLOAT,
    oil_temp_celsius FLOAT,
    fuel_flow_kg_s FLOAT,
    compressor_discharge_temp_celsius FLOAT,
    compressor_discharge_pressure_kpa FLOAT,
    efficiency_fraction FLOAT,
    ambient_temp_celsius FLOAT,
    ambient_pressure_kpa FLOAT,
    vibration_rms_mm_s FLOAT,
    vibration_peak_mm_s FLOAT,
    vibration_crest_factor FLOAT,
    vibration_kurtosis FLOAT,
    num_active_faults INT,
    total_faults_initiated INT,
    upset_active BOOLEAN,
    upset_type VARCHAR(50),
    upset_severity FLOAT,
    vibration_trend_7d FLOAT,
    temp_variation_24h FLOAT,
    speed_stability FLOAT,
    efficiency_degradation_rate FLOAT,
    load_factor FLOAT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS test_data.compressor_telemetry (
    telemetry_id BIGSERIAL PRIMARY KEY,
    compressor_id INT NOT NULL REFERENCES master_data.compressors(compressor_id) ON DELETE CASCADE,
    sample_time TIMESTAMP NOT NULL,
    operating_hours FLOAT,
    speed_rpm FLOAT,
    speed_target_rpm FLOAT,
    flow_m3h FLOAT,
    head_kj_kg FLOAT,
    efficiency_fraction FLOAT,
    power_kw FLOAT,
    suction_pressure_kpa FLOAT,
    suction_temp_celsius FLOAT,
    discharge_pressure_kpa FLOAT,
    discharge_temp_celsius FLOAT,
    surge_margin_percent FLOAT,
    surge_alarm BOOLEAN,
    vibration_amplitude_mm FLOAT,
    sync_amplitude_mm FLOAT,
    shaft_x_displacement_mm FLOAT,
    shaft_y_displacement_mm FLOAT,
    bearing_temp_de_celsius FLOAT,
    bearing_temp_nde_celsius FLOAT,
    thrust_bearing_temp_celsius FLOAT,
    primary_seal_leakage_kg_s FLOAT,
    secondary_seal_leakage_kg_s FLOAT,
    surge_active BOOLEAN,
    surge_cycle_count INT,
    num_active_faults INT,
    total_faults_initiated INT,
    upset_active BOOLEAN,
    upset_type VARCHAR(50),
    upset_severity FLOAT,
    vibration_trend_7d FLOAT,
    temp_variation_24h FLOAT,
    speed_stability FLOAT,
    efficiency_degradation_rate FLOAT,
    pressure_ratio FLOAT,
    load_factor FLOAT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS test_data.pump_telemetry (
    telemetry_id BIGSERIAL PRIMARY KEY,
    pump_id INT NOT NULL REFERENCES master_data.pumps(pump_id) ON DELETE CASCADE,
    sample_time TIMESTAMP NOT NULL,
    operating_hours FLOAT,
    speed_rpm FLOAT,
    speed_target_rpm FLOAT,
    flow_m3h FLOAT,
    head_m FLOAT,
    efficiency_fraction FLOAT,
    power_kw FLOAT,
    suction_pressure_kpa FLOAT,
    discharge_pressure_kpa FLOAT,
    fluid_temp_celsius FLOAT,
    npsh_available_m FLOAT,
    npsh_required_m FLOAT,
    cavitation_margin_m FLOAT,
    cavitation_severity INT,
    vibration_rms_mm_s FLOAT,
    vibration_peak_mm_s FLOAT,
    bearing_temp_de_celsius FLOAT,
    bearing_temp_nde_celsius FLOAT,
    motor_current_amps FLOAT,
    motor_current_ratio FLOAT,
    seal_leakage_rate FLOAT,
    bep_deviation_percent FLOAT,
    temp_variation_24h FLOAT,
    vibration_trend_7d FLOAT,
    speed_stability FLOAT,
    efficiency_degradation_rate FLOAT,
    pressure_ratio FLOAT,
    load_factor FLOAT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_td_gt_turbine_time ON test_data.gas_turbine_telemetry(turbine_id, sample_time DESC);
CREATE INDEX IF NOT EXISTS idx_td_gt_time ON test_data.gas_turbine_telemetry(sample_time DESC);
CREATE INDEX IF NOT EXISTS idx_td_cc_compressor_time ON test_data.compressor_telemetry(compressor_id, sample_time DESC);
CREATE INDEX IF NOT EXISTS idx_td_cc_time ON test_data.compressor_telemetry(sample_time DESC);
CREATE INDEX IF NOT EXISTS idx_td_cp_pump_time ON test_data.pump_telemetry(pump_id, sample_time DESC);
CREATE INDEX IF NOT EXISTS idx_td_cp_time ON test_data.pump_telemetry(sample_time DESC);